name: learn-github-actions
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.16 ]
    steps:

      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install > output.log
      - name: check linters
        run: npm run lint > output.log
      - name: check ts
        run: npm run ts > output.log
      - name: unit test
        run: npm run test > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file


#      - uses: actions/checkout@v3
#      - name: Staring Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}
#      - name: install modules
#        run: npm install
#      - name: check linters
#        run: npm run lint
#      - name: check ts
#        run: npm run ts
#      - name: unit test
#        run: npm run test
#      - name: create docker image
#        run: docker build -t "shri-ci" . --no-cache
#      - name: run docker container on port 3000
#        run: docker run -d -p 3000:80 shri-ci
