name: to-release
on: [push]
jobs:
  init:
    if: startsWith( github.ref, 'refs/tags/rc-')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.16 ]
    steps:

      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: install node_modules
        run: npm ci

      - name: check eslint
        run: npm run lint

      - name: check types
        run: npm run ts

      - name: unit test
        run: npm run test

      - name: Posting ticket
        run: VERSION=${{ github.ref }} ACTOR=${{ github.actor }} GITHUB_TOKEN=${{ github.token }} OAUTH_TOKEN=${{ secrets.OAUTH_TOKEN }} ORG_ID=${{ secrets.ORG_ID }} node postTicket.js


#      - uses: actions/checkout@v3
#      - name: Staring Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}
#      - name: install modules
#        run: npm install
#      - name: check linters
#        run: npm run lint
#      - name: check ts
#        run: npm run ts
#      - name: unit test
#        run: npm run test
#      - name: create docker image
#        run: docker build -t "shri-ci" . --no-cache
#      - name: run docker container on port 3000
#        run: docker run -d -p 3000:80 shri-ci
